### ISSUE TITLE
Taiko plugin system

### ISSUE THREAD

**Issue by zabil** [saikrishna321/taiko-diagnostics#1]
[Draft Proposal]

Introduce diagnostics into a Taiko script. This issue is also a placeholder on what a future plugin architecture for Taiko can look like.

To avoid magic and be clear about plugins in use it's better to choose configuration over convention.

```
const {plugin} = require('taiko')
const diagnostics = require('taiko-diagnostics')
const _ = plugin.load(diagnostics);

_.pageLoadTime(...) // for e.g

```

These plugins should not directly depend on Taiko, but can implement callback that listens to the `load` method and initialises variables that pass Taiko and CRI instances. 

for e.g.
`plugin.load` function
```
function load(plugin) {
 plugin.init(taiko, cri, ....)
}
```

A few things to consider. 
* Must work with typescript
* Must be able to extend and add command line parameters
* Must have the current page context.
* Must be able to invoke all taiko methods.
* Can extend `.api` documentation
* Can add `.` commands like `.step`
* Can be loaded from the command line in case of a REPL `taiko --plugin=diagnostics`

**Comment by sriv** [comment]
Not specific to this use case, but if `taiko` introduces plugin support, perhaps it is worth thinking about some conventions, ex. will the plugins be configured or interpreted as per convention?

examples:

#### configuration:

`package.json` :

```
...
"taiko-plugins" : [
    "diagnostics",
    ...
 ]
...
```

#### convention

`package.json` :

```
...
"devDependencies" : [
    "taiko-diagnostic", //OR
    "@taiko/diagnostics"
]
...
```

The convention approach would require on agreeing on either a prefix or scope. Prefix would let the user create taiko plugins without any gatekeeping from the taiko team. Scoping is probably more controlled.

In either approach, IMO there is value in having some control, so that unintended packages do not get loaded/treated as plugins.

**Comment by zabil** [comment]
DRAFT 2

#### Loading Taiko plugins

```
const {loadPlugin} = require('taiko')
const {pageLoadTime} = loadPlugin("diagnostics")

pageLoadTime(..)
```

or it can also be declared as follows to avoid method name clashes with other plugins.

```
const {loadPlugin} = require('taiko')
const diagnostics = loadPlugin("diagnostics")

diagnostics.pageLoadTime(..)
```

The plugin should be written as follows

```
export default class extends Taiko.Plugin {
  constructor(...) { // Taiko related variables like context etc

  }

 diagnostics (...) {
   // Actions that read the Taiko context
 }
}
```

**Comment by BugDiver** [comment]
# DRAFT 3

## Loading Taiko plugins  and usage

loading 
```js
const { loadPlugin } = require('taiko');
const { ID, clientHandler } = require('taiko-diagnostics');
loadPlugin(ID, clientHandler);
```

usage
```js
const { openBrowser, goto, closeBrowser} = require('taiko');
const { startTracing, endTracing, getSpeedIndex } = require('taiko-diagnostics');

async function main(){
    await openBrowser();
    await startTracing()
    await goto('http://google.com');
    await endTracing();
    let si = await getSpeedIndex();
    console.log(si.speedIndex);
    await closeBrowser();
}

main();

```

#### Combined version 

```js
const { openBrowser, closeBrowser, goto,  loadPlugin } = require('taiko');
const { ID, clientHandler } = require('taiko-diagnostics');
loadPlugin(ID, clientHandler);

async function main(){
    await openBrowser();
    await startTracing()
    await goto('http://google.com');
    await endTracing();
    let si = await getSpeedIndex();
    console.log(si.speedIndex);
    await closeBrowser();
}

main();


```

## Writing plugin 
#### in js
```js
module.exports.ID = "plugin-id"

module.exports.clientHandler = (taiko) => {
   // do anything with taiko instance. All the taiko apis are availavble
   // use taiko.client() to get the CRI instance
  // Store in a gloable variable to use it anywhere
}

module.exports.startTracing = async () => {
  // do something
}

module.exports.stopTracing = async () => {
   // do something more
}

// export all the plugin api's 
...
...
...

```

typescript
```ts
export const ID: string = 'diagnostics';

let _tracingHandler: TracingHandler;

export function clientHandler(taiko: { client: { (): { Tracing: any, IO: any; }; }; }) {
    _tracingHandler = new TracingHandler(taiko.client().Tracing, taiko.client().IO);
}

export async function startTracing() {
    await _tracingHandler.startTracing();
    return { description: 'Browser tracing started' };
}

export async function endTracing() {
    await _tracingHandler.endTracing();
    return { description: 'Browser tracing ended' };
}


...
...
...

```

**Comment by saikrishna321** [comment]
@BugDiver Shouldn't the combined version be 

```
const { openBrowser, closeBrowser, goto,  loadPlugin } = require('taiko');
const { ID, clientHandler, startTracing, endTracing } = require('taiko-diagnostics');
loadPlugin(ID, clientHandler);
```

**Comment by BugDiver** [comment]
@saikrishna321  You are right. I  have updated it. Thanks for pointing it out.
