### ISSUE TITLE
Add support for capturing logs from Runtime.exceptionThrown

### ISSUE THREAD

**Issue by negiDharmendra** [saikrishna321/taiko-diagnostics#16]
User should be able to see any unhandled exception using [logConsoleInfo](https://github.com/saikrishna321/taiko-diagnostics#logconsoleinfo-command) API.

**Comment by saikrishna321** [comment]
https://github.com/getgauge/taiko/issues/322

**Comment by negiDharmendra** [comment]
I will create a PR for this.
