### ISSUE TITLE
Printing entire JSON object on STDOUT creates too much noise.

### ISSUE THREAD

**Issue by negiDharmendra** [saikrishna321/taiko-diagnostics#18]
The current implementation prints the entire JSON object which is too much noise to look at.
I would say that just print enough information to indicate the failure (The way we see on the browser console) and emit some custom events. User can subscribe to those custom events if they want to.

**Example:** 
Instead of printing
> {"source":"network","level":"error","text":"Failed to load resource: the server responded with a status of 404 ()","timestamp":1555476739348.25,"url":"https://example.com/style.css","networkRequestId":"1000002710.3"}

Print 
> Failed to load resource: the server responded with a status of 404 ().  
    Resource: https://example.com/style.css

**Comment by saikrishna321** [comment]
@negiDharmendra How about just printing the error 

> "Failed to load resource: the server responded with a status of 404

**Comment by negiDharmendra** [comment]
I think the information is not enough. As it does not tell us about the resource.

**Comment by negiDharmendra** [comment]
getgauge/taiko#322
